---
- name: Create Ryu virtualenv
  command: python3 -m venv /home/student/venvs/ryu
  args:
    creates: /home/student/venvs/ryu

- name: Install Ryu in venv
  shell: |
    /home/student/venvs/ryu/bin/pip install --upgrade pip "setuptools<68" wheel
    /home/student/venvs/ryu/bin/pip install ryu
