---
- name: Ryu Image bauen
  community.docker.docker_container:
    name: ryu-controller
    source: build
    build:
      path: ./docker/ryu

- name: Ryu Container starten
  community.docker.docker_container:
    name: ryu-controller
    image: ryu-controller
    state: started
    network_mode: host
    volumes:
      - /home/student/Software-Defined-Networking:/mnt/Software-Defined-Networking
